name: Flutter Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # Specify the Flutter version you are using
        channel: 'stable'  # or 'beta' or 'dev'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-${{ github.run_number }}
        path: build/windows/x64/runner/Release/*